### ISSUE TITLE
Misc. small improvements worth doing

### ISSUE THREAD

**Issue by ndorfin** [nzruby/conf#39]
Hi! 🖖 

Here are some things I could do for the site, if needs be:

- [x] Wrap the Google Analytics script in a [DoNotTrack](http://donottrack.us/) check. Being nice web neighbours.
- [x] Incorporate the GA Script in the global JS. Doing so reduces the HTML weight, and adds cacheability to the script that invokes GA.
- [ ] Add Schema.org metadata where it counts.
- [ ] CSS audit - clean up unused CSS, break it up into partials. See: #72 
- [ ] Expose sponsors as independent URLs
- [ ] Expose speakers as independent URLs
- [ ] Expose the venue as an independent URL

Tick all those you'd like me to tackle :)

-S

**Comment by mermop** [comment]
What do you mean by exposing speakers and sponsors as independent URLs? Like putting a little 🔗 somewhere so people can link to eg http://kiwi.ruby.nz/speakers/#eoin ?

If we're going to do that for speakers and sponsors it's probably worth doing it for side events as well.

As an aside we need to put in something so that # links take into account the height of the nav - either anchor tags that are a little higher than the elements we're linking to or some js that scrolls to the right place

**Comment by mermop** [comment]
Any of those seem worthy but also not urgent - do whatever brings you joy @ndorfin

**Comment by ndorfin** [comment]
@mermop 
I mean having pages for each speaker / sponsor / side-event, and a sponsors page that lists all sponsors:

- For each speaker page, you can list their talks / workshops.
- For each sponsor page you can list what talks/workshops that sponsor is supporting.

**Comment by mermop** [comment]
Ah right. Nah I don't think it's worth doing a separate page for each speaker or even each side event. I'd want to get our design friends at Icelab involved if we did that and there's other stuff I'd rather they spend their time on. We don't have that much info about each speaker, I think it's fine to have them all on one and link to them with /speakers#their-name - that said we do need to improve the #-linking behaviour as above

Separate sponsors page could be worth doing - leave that one to me though

**Comment by ndorfin** [comment]
Issued #43 to address Google Analytics
